version: '3.9'
networks:
  chat-gpt-network:
    name: "chat-gpt-network"
    ipam:
      config:
        - subnet: 172.30.0.0/24
services:
  postgres:
    image: 'postgres:15.2'
    container_name: 'chat-gpt-database'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ratazana32145 # for local test
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5448:5442'
    networks:
      chat-gpt-network:
        ipv4_address: 172.30.0.2
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/Functions.sql:/docker-entrypoint-initdb.d/01_functions.sql
      - ./sql/CreateTables.sql:/docker-entrypoint-initdb.d/02_createTables.sql
      - ./sql/Triggers.sql:/docker-entrypoint-initdb.d/03_triggers.sql
      - ./sql/InsertUser.sql:/docker-entrypoint-initdb.d/04_insertUser.sql